// Copyright (c) RoochNetwork
// SPDX-License-Identifier: Apache-2.0

//**
//  *  ######################################
//  *  ### DO NOT EDIT THIS FILE DIRECTLY ###
//  *  ######################################
//  *
//  * This file is generated from:
//  * /rooch-sdk/test-e2e
//  */
export const snapshoot = []
